### ISSUE TITLE
Crash - mrtjp/projectred/expansion/TileFrameMotor

### ISSUE THREAD

**Issue by mgwerner** [MrTJP/ProjectRed#1018]
---- Minecraft Crash Report ----
// There are four lights!

Time: 4/7/16 4:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mrtjp/projectred/expansion/TileFrameMotor
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at magic.launcher.Launcher.main(SourceFile:214)
Caused by: java.lang.NoClassDefFoundError: mrtjp/projectred/expansion/TileFrameMotor
    at mrtjp.projectred.expansion.ExpansionProxy_server.init(proxies.scala:61)
    at mrtjp.projectred.expansion.ExpansionProxy_client.init(proxies.scala:114)
    at mrtjp.projectred.ProjectRedExpansion$.init(ProjectRedExpansion.scala:46)
    at mrtjp.projectred.ProjectRedExpansion.init(ProjectRedExpansion.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 15 more
Caused by: java.lang.ClassNotFoundException: mrtjp.projectred.expansion.TileFrameMotor
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 45 more
Caused by: java.lang.NoClassDefFoundError: mrtjp/projectred/expansion/TMotorTile
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 47 more
Caused by: java.lang.ClassNotFoundException: mrtjp.projectred.expansion.TMotorTile
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 51 more
Caused by: java.lang.NoClassDefFoundError: mrtjp/mcframes/api/IFrame
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 53 more
Caused by: java.lang.ClassNotFoundException: mrtjp.mcframes.api.IFrame
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 57 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_77, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3289183656 bytes (3136 MB) / 4214489088 bytes (4019 MB) up to 4214489088 bytes (4019 MB)
    JVM Flags: 28 total; -Xmx8G -Xms3G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -Xms4096m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 75 mods loaded, 75 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHI    Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHI    appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core](minecraft.jar) 
    UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHI    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) 
    UCHI    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHI    NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHI    OpenComputers|Core{1.5.22.46} [OpenComputers (Core)](minecraft.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHI    Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHI    AgriCraft{1.7.10-1.5.0} [AgriCraft](AgriCraft-1.7.10-1.5.0.jar) 
    UCHI    AppleCore{1.0.2} [AppleCore](AppleCore-mc1.7.10-1.0.2.jar) 
    UCHI    appliedenergistics2{rv3-beta-5} [Applied Energistics 2](appliedenergistics2-rv3-beta-5.jar) 
    UCHI    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) 
    UCHI    BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCHI    ExtrabiomesXL{3.16.2} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.2.jar) 
    UCHI    BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition](BiblioWoods[ExtraBiomesXL][v1.4].jar) 
    UCHI    CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHI    BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHI    ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHI    ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    IC2{2.2.819-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.819-experimental.jar) 
    UCHI    Railcraft{9.6.1.0} [Railcraft](Railcraft_1.7.10-9.6.1.0.jar) 
    UCHI    chisel{2.9.3.9} [Chisel](Chisel-2.9.3.9.jar) 
    UCHI    lootablebodies{1.3.5} [DrCyano's Lootable Bodies](CyanosLootableBodies-1.3.5-backport.jar) 
    UCHI    Enchiridion{1.1} [Enchiridion](Enchiridion-1.7.X-1.2b.jar) 
    UCHI    EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UCHI    FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) 
    UCHI    McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
    UCHI    GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.402.jar) 
    UCHI    GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.402.jar) 
    UCHI    HopperDuctMod{1.3.2} [Hopper Ducts](hopperductmod-1.7.10-1.3.2.jar) 
    UCHI    IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2](IC2NuclearControl-2.2.5a-GoingForTheKill.jar) 
    UCHI    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHI    latticemod{1.0} [Lattice Mod](latticemod-mc1.7.10-1.0.jar) 
    UCHI    llibrary{0.4.1} [LLibrary](llibrary-0.4.1-1.7.10.jar) 
    UCHI    MapWriter{2.1710.1} [MapWriter](MapWriter-1.7.10-2.1710.2.jar) 
    UCHI    Mariculture{1.7.10-1.2.4.2a} [Mariculture](Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
    UCHI    MariTech{1.0} [Marine Technlogy](Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
    UCHI    MorePlanet{1.3.0} [More Planets](More-Planets-1.7.10-1.3.0-Pre-1.jar) 
    UCHI    MrTJPCoreMod{1.1.0.33} [MrTJPCore](MrTJPCore-1.1.0.33-universal.jar) 
    UCHI    NEIAddons{1.12.8.29} [NEI Addons](neiaddons-1.12.8.29-mc1.7.10.jar) 
    UCHI    NEIAddons|AppEng{1.12.8.29} [NEI Addons: Applied Energistics 2](neiaddons-1.12.8.29-mc1.7.10.jar) 
    UCHI    NEIAddons|Botany{1.12.8.29} [NEI Addons: Botany](neiaddons-1.12.8.29-mc1.7.10.jar) 
    UCHI    NEIAddons|Forestry{1.12.8.29} [NEI Addons: Forestry](neiaddons-1.12.8.29-mc1.7.10.jar) 
    UCHI    NEIAddons|CraftingTables{1.12.8.29} [NEI Addons: Crafting Tables](neiaddons-1.12.8.29-mc1.7.10.jar) 
    UCHI    NEIAddons|ExNihilo{1.12.8.29} [NEI Addons: Ex Nihilo](neiaddons-1.12.8.29-mc1.7.10.jar) 
    UCHI    neiintegration{1.0.9} [NEI Integration](NEIIntegration-MC1.7.10-1.0.9.jar) 
    UCHI    ProjRed|Core{4.7.0pre12.95} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
    UCHI    ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHI    OpenComputers{1.5.22.46} [OpenComputers](OpenComputers-MC1.7.10-1.5.22.46-universal.jar) 
    UCHI    ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHI    ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
    UCHI    ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
    UCHI    ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHI    ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
    UCHI    ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
    UCHE    ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHI    qCraft{1.2} [qCraft](qCraft1.2.zip) 
    UCHI    QuarryPlus{2.1.0} [QuarryPlus](QuarryPlus-1.7.10-2.1.0.jar) 
    UCHI    SGCraft{1.9.3} [Greg's SG Craft](SGCraft-1.9.3-mc1.7.10.jar) 
    UCHI    SpiceOfLife{1.2.3} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.3.jar) 
    UCHI    TallDoors{0.5.1} [Tall Doors Mod](TallDoors-1.7.10-0.5.2.jar) 
    UCHI    chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)](VillageInfoSSP-1.7.10-2.1.jar) 
    UCHI    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHI    WailaHarvestability{1.1.1} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.1.jar) 
    UCHI    wawla{1.1.1} [What Are We Looking At](Wawla-1.1.1_1.7.10.jar) 
    UCHI    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.87' Renderer: 'GeForce GT 640M LE/PCIe/SSE2'
    AE2 Version: beta rv3-beta-5 for Forge 10.13.4.1448
    CoFHCore: -[1.7.10]3.0.3-303

**Comment by mgwerner** [comment]
Nevermind, found the issue was not enabling the jars in the launcher.  My apologies for wasting your time.
