### ISSUE TITLE
Crash with EnderIO

### ISSUE THREAD

**Issue by Rob5Underscores** [MrTJP/ProjectRed#1054]
`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 01/08/16 15:56
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 9
    at mrtjp.core.inventory.TInventory$class.getStackInSlot(invtraits.scala:33)
    at mrtjp.projectred.expansion.TileFilteredImporter.func_70301_a(TileFilteredImporter.scala:31)
    at crazypants.enderio.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:162)
    at crazypants.enderio.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:113)
    at crazypants.enderio.conduit.item.ItemConduitNetwork.doNetworkTick(ItemConduitNetwork.java:214)
    at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:63)
    at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_278_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:894)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by Scrik** [comment]
UP,crash with enderIO
http://pastebin.com/q23Xr1s5
Please fix
