### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Tolynook** [MrTJP/ProjectRed#1065]
[crash-2016-09-04_18.15.27-server.txt](https://github.com/MrTJP/ProjectRed/files/453986/crash-2016-09-04_18.15.27-server.txt)

[18:15:27 ERROR]: Provided chunk is null for (-16, 2) !
[18:15:27 ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$WorldTickEvent@be1f5b0:
net.minecraft.util.ReportedException: Exception getting block type in world
        at net.minecraft.world.World.func_147439_a(World.java:711) ~[ahb.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$$anonfun$ncheck$1.apply$mcVI$sp(MossSpreadHandler.scala:82) ~[MossSpreadHandler$$anonfun$ncheck$1.class:?]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166) ~[scala-library-2.11.7.jar:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.ncheck(MossSpreadHandler.scala:79) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.isBlockHot(MossSpreadHandler.scala:71) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.crackFromHeat(MossSpreadHandler.scala:36) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.onBlockUpdate(MossSpreadHandler.scala:25) ~[MossSpreadHandler$.class:?]
        at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:101) ~[BlockUpdateHandler$.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_180_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.58]
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260) [FMLCommonHandler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.World.func_147439_a(World.java:703) ~[ahb.class:?]
        ... 16 more
[18:15:27 ERROR]: Index: 6 Listeners:
[18:15:27 ERROR]: 0: NORMAL
[18:15:27 ERROR]: 1: ASM: ic2.core.TickHandler@192b38d6 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[18:15:27 ERROR]: 2: ASM: codechicken.nei.ServerHandler@5a9a538d tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[18:15:27 ERROR]: 3: ASM: forestry.core.TickHandlerCoreServer@5a5dc944 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[18:15:27 ERROR]: 4: ASM: forestry.core.multiblock.MultiblockServerTickHandler@1d20177e onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[18:15:27 ERROR]: 5: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@3dcf6048 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[18:15:27 ERROR]: 6: ASM: mrtjp.core.world.BlockUpdateHandler$@2fe625ec onTick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[18:15:27 ERROR]: 7: ASM: buildcraft.transport.stripes.PipeExtensionListener@ed36558 tick(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[18:15:27 ERROR]: 8: ASM: buildcraft.robotics.map.MapManager@189ee128 tickDelayedWorlds(Lcpw/mods/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[18:15:27 ERROR]: 9: ASM: appeng.hooks.TickHandler@5670f7e4 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[18:15:27 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception getting block type in world
        at net.minecraft.world.World.func_147439_a(World.java:711) ~[ahb.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$$anonfun$ncheck$1.apply$mcVI$sp(MossSpreadHandler.scala:82) ~[MossSpreadHandler$$anonfun$ncheck$1.class:?]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166) ~[scala-library-2.11.7.jar:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.ncheck(MossSpreadHandler.scala:79) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.isBlockHot(MossSpreadHandler.scala:71) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.crackFromHeat(MossSpreadHandler.scala:36) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.onBlockUpdate(MossSpreadHandler.scala:25) ~[MossSpreadHandler$.class:?]
        at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:101) ~[BlockUpdateHandler$.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_180_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.58]
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260) ~[FMLCommonHandler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.World.func_147439_a(World.java:703) ~[ahb.class:?]
        ... 16 more
[18:15:27 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at net.minecraft.world.World.func_147439_a(World.java:703) ~[ahb.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$$anonfun$ncheck$1.apply$mcVI$sp(MossSpreadHandler.scala:82) ~[MossSpreadHandler$$anonfun$ncheck$1.class:?]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166) ~[scala-library-2.11.7.jar:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.ncheck(MossSpreadHandler.scala:79) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.isBlockHot(MossSpreadHandler.scala:71) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.crackFromHeat(MossSpreadHandler.scala:36) ~[MossSpreadHandler$.class:?]
        at mrtjp.projectred.exploration.MossSpreadHandler$.onBlockUpdate(MossSpreadHandler.scala:25) ~[MossSpreadHandler$.class:?]
        at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:101) ~[BlockUpdateHandler$.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_180_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.58]
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260) ~[FMLCommonHandler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by MrTJP** [comment]
Non-issue, since moss spreading will be removed completely unless I can rewrite it.
