### ISSUE TITLE
[1.10.2] client disconnecting when chaning timer interval

### ISSUE THREAD

**Issue by enricotagliavini** [MrTJP/ProjectRed#1122]
ProjectRed version: 4.8.0.17
MrTJPCore version: 2.0.0.12

Steps to reproduce:
1. place down a timer from integration mod
2. right click the timer
3. increase the timer by +1s

Client will disconnect immediately and the server will show the following in the console. Server doesn't crash though, client can reconnect immediately. However the timer interval is not change, hence it is impossible to have a different timer other than the default one.

```
[14:21:09] [Netty Epoll Server IO #5/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (22 > 20)
        at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:380) ~[eq.class:?]
        at net.minecraft.network.play.client.CPacketCustomPayload.func_148837_a(CPacketCustomPayload.java:34) ~[it.class:?]
        at net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40) ~[er.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) ~[ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) ~[ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]                                                                             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]                                                           at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]                                                             at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [ReadTimeoutHandler.class:?]                                                                                          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]                                                           at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:?]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [EpollSocketChannel$EpollSocketUnsafe.class:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [EpollEventLoop.class:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [EpollEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[14:21:09] [Netty Epoll Server IO #5/ERROR] [FML]: NetworkDispatcher exception                                                                                                                                io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (174063615 > 131068)                                                                                at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:368) ~[eq.class:?]                                                                                                                      at net.minecraft.network.play.client.CPacketTabComplete.func_148837_a(SourceFile:31) ~[il.class:?]                                                                                                            at net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40) ~[er.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) ~[ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:205) ~[ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ChannelInboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ChannelInboundHandlerAdapter.class:?]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [ReadTimeoutHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [AbstractChannel$AbstractUnsafe$5.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [EpollEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[14:21:09] [Server thread/INFO]: IcoSauro lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (22 > 20)], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[14:21:09] [Server thread/INFO]: IcoSauro left the game
```

System details and mod list / version (yes this is from a crash report, but it is totally unrelated to this issue)
```
        Minecraft Version: 1.10.2
        Operating System: Linux (amd64) version 3.10.0-514.6.1.el7.x86_64
        Java Version: 1.8.0_121, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 92822040 bytes (88 MB) / 1209532416 bytes (1153 MB) up to 2863661056 bytes (2731 MB)
        JVM Flags: 1 total; -Xmx3072M
        IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
        FML: MCP 9.32 Powered by Forge 12.18.3.2221 49 mods loaded, 49 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
        UCHIJAAAA       FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221-universal.jar)
        UCHIJAAAA       Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221-universal.jar)
        UCHIJAAAA       NotEnoughItems{2.1.3.199} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.199-universal.jar)
        UCHIJAAAA       ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
        UCHIJAAAA       battletowers{1.5.5} [Battle Towers] (BattleTowers-1.10.2.jar)
        UCHIJAAAA       Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar)
        UCHIJAAAA       bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.4.jar)
        UCHIJAAAA       infinitylib{1.10.2-0.6.0} [InfinityLib] (infinitylib-0.6.0.jar)
        UCHIJAAAA       boatlantern{1.10.2-0.4.0} [Lantern] (boatlantern-0.4.0.jar)
        UCHIJAAAA       Botania{r1.9-340} [Botania] (Botania r1.9-340.jar)
        UCHIJAAAA       CodeChickenLib{2.5.2.198} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
        UCHIJAAAA       brandonscore{2.1.3} [Brandon's Core] (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
        UCHIJAAAA       ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter-1.10.2-2.5.6.jar)
        UCHIJAAAA       chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar)
        UCHIJAAAA       CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar)
        UCHIJAAAA       draconicevolution{2.0.7} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.7.168-universal.jar)
        UCHIJAAAA       endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar)
        UCHIJAAAA       JEI{3.14.2.401} [Just Enough Items] (jei_1.10.2-3.14.2.401.jar)
        UCHIJAAAA       Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar)
        UCHIJAAAA       EnderIO{1.10.2-3.1.161} [Ender IO] (EnderIO-1.10.2-3.1.161.jar)
        UCHIJAAAA       extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.2.0.jar)
        UCHIJAAAA       fairylights{2.0.6} [Fairy Lights] (fairylights-2.0.6-1.10.2.jar)
        UCHIJAAAA       forestry{5.2.17.360} [Forestry] (forestry_1.10.2-5.2.17.360.jar)
        UCHIJAAAA       forgemultipartcbe{2.0.0.24} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.24-universal.jar)
        UCHIJAAAA       microblockcbe{2.0.0.24} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.24-universal.jar)
        UCHIJAAAA       minecraftmultipartcbe{2.0.0.24} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.24-universal.jar)
        UCHIJAAAA       mantle{1.10.2-1.1.4.203} [Mantle] (Mantle-1.10.2-1.1.4.jar)
        UCHIJAAAA       tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar)
        UCHIJAAAA       immersiveengineering{0.10-56} [Immersive Engineering] (ImmersiveEngineering-0.10-56.jar)
        UCHIJAAAA       InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.10-1.4.9.jar)
        UCHIJAAAA       ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar)
        UCHIJAAAA       journeymap{1.10.2-5.4.4} [JourneyMap] (journeymap-1.10.2-5.4.4.jar)
        UCHIJAAAA       mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar)
        UCHIJAAAA       minecolonies{1.10.2-0.6.2849} [MineColonies] (minecolonies-universal-1.10.2-0.6.2849.jar)
        UCHIJAAAA       MrTJPCoreMod{2.0.0.12} [MrTJPCore] (MrTJPCore-1.10.2-2.0.0.12-universal.jar)
        UCHIJAAAA       parachutemod{1.5.2} [Parachute Mod] (parachutemod-ng-1.10.2-1.5.2-416.jar)
        UCHIJAAAA       projectred-core{4.8.0.17} [ProjectRed Core] (ProjectRed-1.10.2-4.8.0.17-Base.jar)
        UCHIJAAAA       projectred-integration{4.8.0.17} [ProjectRed integration] (ProjectRed-1.10.2-4.8.0.17-integration.jar)
        UCHIJAAAA       projectred-transmission{4.8.0.17} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.0.17-integration.jar)
        UCHIJAAAA       projectred-illumination{4.8.0.17} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.0.17-lighting.jar)
        UCHIJAAAA       railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar)
        UCHIJAAAA       reliquia{0.0.7} [Reliquia] (Reliquia-[1.10.2]-0.0.7.jar)
        UCHIJAAAA       Roguelike{1.5.6} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.6.jar)
        UCHIJAAAA       ruins{16.2} [Ruins Mod] (Ruins-1.10.2.jar)
        UCHIJAAAA       sgcraft{1.13.2} [SG Craft] (SGCraft-1.13.2-mc1.10.2.jar)
        UCHIJAAAA       tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar)
        UCHIJAAAA       icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar)
        UCHIJAAAA       wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar)
        Loaded coremods (and transformers):
```

Feel free to ask if more information is required.

**Comment by enricotagliavini** [comment]
I tried to reproduce in single player and I cannot. This seems to happen only in SMP servers

**Comment by jerry1333** [comment]
I think it's fixed in 423ef5ad0f44290a28b1e2fa29ed08bafa7585b4

**Comment by enricotagliavini** [comment]
That's a good news! Do you have any plan for a release in, let's say, ~1 month? No pressure intended just to be clear, it's just for my own information and organization. If not I can test a pre-release if you have a build server, if you want.

Thank you!

**Comment by MrTJP** [comment]
Probably a few days..

**Comment by enricotagliavini** [comment]
Hello! Just want to confirm I updated to ProjectRed 4.8.1.25 (including required deps) and the issue is fixed!

Thank you very much!
