### ISSUE TITLE
[1.10.2] PR:Illumination - Client crashes after looking up recipe in JEI

### ISSUE THREAD

**Issue by SanAndreasP** [MrTJP/ProjectRed#1156]
Minecraft: 1.10.2
Forge: 12.18.3.2254
MrTJPCore: 2.0.0.14
ProjectRed Core: 4.8.1.25
ProjectRed Illumination: 4.8.1.25

I tried to look up a recipe from another mod and suddenly my game crashed with a NoClassDefFoundError:
```
java.lang.NoClassDefFoundError: mrtjp/projectred/transmission/WireDef$
	at mrtjp.projectred.illumination.TButtonItemRendererCommons$class.renderButtonInventory(buttonpart.scala:257)
	at mrtjp.projectred.illumination.ButtonItemRenderer$.renderButtonInventory(buttonpart.scala:280)
	at mrtjp.projectred.illumination.TButtonItemRendererCommons$class.renderItem(buttonpart.scala:245)
	at mrtjp.projectred.illumination.ButtonItemRenderer$.renderItem(buttonpart.scala:280)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86)
	at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:167)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:231)
	at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:303)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:27)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderSlow(GuiIngredientFast.java:183)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderSlow(GuiIngredientFast.java:173)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:194)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1739_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at appeng.client.gui.AEBaseGui.func_73863_a(AEBaseGui.java:161)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mrtjp.projectred.transmission.WireDef$
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```

Complete log:
https://gist.githubusercontent.com/SanAndreasP/02f334ef730cbcb7b34a2fa0d1da8e45/raw/1c346119e6b8cabf166b7ee3dc5a90438b3c27db/latest.log

**Comment by MrTJP** [comment]
Already fixed. Changes will be in the next release. 657f6065ed139ea0fbb5d1a4234008ab19b91e9d
