### ISSUE TITLE
[1.7.10]Electrotine Power enegy is crash

### ISSUE THREAD

**Issue by friksasha** [MrTJP/ProjectRed#1163]
minecraft 1.7.10 Forge-1614
Thermos-1.7.10-1614-server
ProjectRed-1.7.10-4.7.0pre12.95
![2017-04-24_21 22 25](https://cloud.githubusercontent.com/assets/25547088/25352710/a36bdf38-2935-11e7-8c1b-b91ea992e2b7.png)
![2017-04-24_21 22 32](https://cloud.githubusercontent.com/assets/25547088/25352713/a61836fa-2935-11e7-948e-44ff8f4a9167.png)
![2017-04-24_21 22 46](https://cloud.githubusercontent.com/assets/25547088/25352717/a780e992-2935-11e7-9c65-cf0fe43f6a61.png)
What happened? In what side to dig?

**Comment by friksasha** [comment]
Also there was a crash with a string on the batterybox.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 24.04.17 22:24
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -107366
	at mrtjp.projectred.expansion.RenderBatteryBox$.getData(TileBatteryBox.scala:314)
	at mrtjp.core.render.TCubeMapRender$class.renderWorldBlock(TCubeMapRender.scala:40)
	at mrtjp.projectred.expansion.RenderBatteryBox$.renderWorldBlock(TileBatteryBox.scala:305)
	at mrtjp.core.block.TileRenderRegistry$.renderWorldBlock(tileblock.scala:102)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
	at mrtjp.projectred.expansion.RenderBatteryBox$.getData(TileBatteryBox.scala:314)
	at mrtjp.core.render.TCubeMapRender$class.renderWorldBlock(TCubeMapRender.scala:40)
	at mrtjp.projectred.expansion.RenderBatteryBox$.renderWorldBlock(TileBatteryBox.scala:305)
	at mrtjp.core.block.TileRenderRegistry$.renderWorldBlock(tileblock.scala:102)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 539236616 bytes (514 MB) / 1408360448 bytes (1343 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Forge 10.13.4.1614 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	da3dsoulASMFix{0.1.0} [DA3DSOUL ASM Fixes] (minecraft.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	OpenComputers|Core{1.6.2.12} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJA	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHIJA	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCHIJA	ChocoPatcher{1.2} [Choco Patcher] (minecraft.jar) 
	UCHIJA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJA	Treecapitator{1.7.10} [Treecapitator] (1.7.10Treecapitator_universal_2.0.4.jar) 
	UCHIJA	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHIJA	BuildCraft|Core{7.1.20} [BuildCraft] (buildcraft-7.1.20.jar) 
	UCHIJA	BuildCraft|Factory{7.1.20} [BC Factory] (buildcraft-7.1.20.jar) 
	UCHIJA	BuildCraft|Transport{7.1.20} [BC Transport] (buildcraft-7.1.20.jar) 
	UCHIJA	BuildCraft|Energy{7.1.20} [BC Energy] (buildcraft-7.1.20.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.20} [BC Silicon] (buildcraft-7.1.20.jar) 
	UCHIJA	BuildCraft|Builders{7.1.20} [BC Builders] (buildcraft-7.1.20.jar) 
	UCHIJA	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7.1release4.0.9.jar) 
	UCHIJA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJA	BuildCraft|Robotics{7.1.20} [BC Robotics] (buildcraft-7.1.20.jar) 
	UCHIJA	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UCHIJA	BuildCraft|Compat{7.1.6} [BuildCraft Compat] (buildcraft-compat-7.1.6.jar) 
	UCHIJA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b-fix3.jar) 
	UCHIJA	FloodLights{1.2.8-137} [Flood Lights] (FloodLights-1.7.10-1.2.8-137.jar) 
	UCHIJA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.487.jar) 
	UCHIJA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.487.jar) 
	UCHIJA	GalaxySpace{1.1.4} [GalaxySpace] (GalaxySpace-1.1.4 STABLE.jar) 
	UCHIJA	GollumCoreLib{2.0.0} [Gollum Core Lib] (GollumCoreLib-2.0.0-1.7.10.jar) 
	UCHIJA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3-fix.jar) 
	UCHIJA	IC2NuclearControl{2.0.8c} [Nuclear Control 2] (IC2NuclearControl-2.0.8c.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	JammyFurniture{5.0.0 [Build Smeagol]} [Jammy Furniture Mod] (JammyFurniture-5.0.0-1.7.10.jar) 
	UCHIJA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJA	OpenComputers{1.6.2.12} [OpenComputers] (OpenComputers-MC1.7.10-1.6.2.12-universal.jar) 
	UCHIJA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-RUS-1.7.10-1.1.jar) 
	UCHIJA	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UCHIJA	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	UCHIJA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHIJA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	xact{0.5.2} [XACT] (XACT-1.7.10-0.5.4c.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.78, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by friksasha** [comment]
Why is the voltage not reset?
![2017-04-25_18 54 06](https://cloud.githubusercontent.com/assets/25547088/25395092/9ef5ecec-29e8-11e7-945c-c33215295153.png)

**Comment by friksasha** [comment]
Okay. I do not want to understand electricity. And I do not want to make a commit. I will say so.
Problem in the server. The client is working fine. I tested several version KCauldron and your fork.
I fixed thit problem as follows:
In file \src\mrtjp\projectred\core\powertraits.scala I added the following lines:
Vloc = math.abs(Vloc) Voltage went into negative
if (Vloc > 120) {Vloc = 120}
