### ISSUE TITLE
Server needs "ProjectRed|Core"

### ISSUE THREAD

**Issue by TheRedFreak** [MrTJP/ProjectRed#1215]
Hi,

i tried to start a server with Project red etc but i keep getting this error:

> 
    [11:06:07] [Server thread/ERROR]: Encountered an unexpected exception cpw.mods.fml.common.MissingModsException:
    Missing Mods:
             ProjRed|Core : any

        at cpw.mods.fml.common.Loader.sortModList(Loader.java:243) ~[Loader.class:?]
        at cpw.mods.fml.common.Loader.loadMods(Loader.java:493) ~[Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

Also i keep getting 
> java.util.zip.ZipException: error in opening zip file

which is CodeChicken's problem (i think)

btw. here's full startup log: [here](https://pastebin.com/ZNqGpw91)

**Comment by MrTJP** [comment]
All i can say is maybe try downloading the file again. Other than that, update to a more recent version of PR.
