### ISSUE TITLE
[1.7.10] Breaking microblock using IC2 drill causes crash

### ISSUE THREAD

**Issue by ensirius** [MrTJP/ProjectRed#1227]
```java
java.lang.ArrayIndexOutOfBoundsException: 16
  at net.minecraft.block.Block.isToolEffective(Block.java:2257)
  at net.minecraftforge.common.ForgeHooks.isToolEffective(ForgeHooks.java:157)
  at net.minecraft.item.ItemTool.getDigSpeed(ItemTool.java:128)
  at ic2.core.item.tool.ItemElectricTool.getDigSpeed(ItemElectricTool.java:148)
  at ic2.core.item.tool.ItemDrill.getDigSpeed(ItemDrill.java:64)
  at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:920)
  at codechicken.microblock.BlockMicroMaterial.getStrength(BlockMicroMaterial.scala:98)
  at codechicken.microblock.Microblock.getStrength(Microblock.scala:44)
  at codechicken.multipart.BlockMultipart.func_149737_a(BlockMultipart.scala:205)
```

**Comment by ensirius** [comment]
I just found #1057. Red power version `4.7.0pre12.95`

**Comment by MrTJP** [comment]
This is no longer an issue
