### ISSUE TITLE
Transmission Error

### ISSUE THREAD

**Issue by crazedslawplays** [MrTJP/ProjectRed#1252]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SoundFixPatchingLoader (AmbientSounds_v2.2.3_mc1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 3/17/18 5:50 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from projectred-transmission (projectred-transmission)
Caused by: java.lang.NoClassDefFoundError: mrtjp/projectred/transmission/ItemPartFramedWire
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.getDeclaredMethods(Class.java:1967)
	at net.minecraftforge.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:393)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:576)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mrtjp.projectred.transmission.ItemPartFramedWire
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Caused by: java.lang.NoClassDefFoundError: mrtjp/core/item/ItemCore
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more
Caused by: java.lang.ClassNotFoundException: mrtjp.core.item.ItemCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 108927056 bytes (103 MB) / 335544320 bytes (320 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2628 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version           | Source                                        | Signature                                |
	|:----- |:------------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                 | 1.12.2            | minecraft.jar                                 | None                                     |
	| UC    | mcp                       | 9.42              | minecraft.jar                                 | None                                     |
	| UC    | FML                       | 8.0.99.99         | forge-1.12.2-14.23.2.2628.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                     | 14.23.2.2628      | forge-1.12.2-14.23.2.2628.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | opencomputers|core        | 1.7.2.67          | minecraft.jar                                 | None                                     |
	| UC    | mercurius_updater         | 1.0               | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UC    | ambientsounds             | 2.0.0             | AmbientSounds_v2.2.3_mc1.12.2.jar             | None                                     |
	| UC    | bdlib                     | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                  | None                                     |
	| UC    | buildcraftlib             | 7.99.15           | buildcraft-7.99.15.jar                        | None                                     |
	| UC    | buildcraftcore            | 7.99.15           | buildcraft-7.99.15.jar                        | None                                     |
	| UC    | buildcraftbuilders        | 7.99.15           | buildcraft-7.99.15.jar                        | None                                     |
	| UC    | buildcraftenergy          | 7.99.15           | buildcraft-7.99.15.jar                        | None                                     |
	| UC    | buildcraftfactory         | 7.99.15           | buildcraft-7.99.15.jar                        | None                                     |
	| UC    | buildcraftrobotics        | 7.99.15           | buildcraft-7.99.15.jar                        | None                                     |
	| UC    | buildcraftsilicon         | 7.99.15           | buildcraft-7.99.15.jar                        | None                                     |
	| UC    | buildcrafttransport       | 7.99.15           | buildcraft-7.99.15.jar                        | None                                     |
	| UC    | codechickenlib            | 3.1.6.339         | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | enderstorage              | 2.4.2.126         | EnderStorage-1.12.2-2.4.2.126-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | energyconverters          | 1.0.1.2           | energyconverters_1.12.1-1.0.1.2.jar           | None                                     |
	| UC    | forgemultipartcbe         | 2.4.0.55          | ForgeMultipart-1.12.2-2.4.0.55-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | microblockcbe             | 2.4.0.55          | ForgeMultipart-1.12.2-2.4.0.55-universal.jar  | None                                     |
	| UC    | minecraftmultipartcbe     | 2.4.0.55          | ForgeMultipart-1.12.2-2.4.0.55-universal.jar  | None                                     |
	| UC    | advgenerators             | 0.9.20.12         | generators-0.9.20.12-mc1.12.2.jar             | None                                     |
	| UC    | ironchest                 | 1.12.2-7.0.40.824 | ironchest-1.12.2-7.0.40.824.jar               | None                                     |
	| UC    | jei                       | 4.8.5.159         | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| UC    | nei                       | 2.4.1             | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | opencomputers             | 1.7.2.67          | OpenComputers-MC1.12.2-1.7.2.67.jar           | None                                     |
	| UC    | projecte                  | 1.12-PE1.0.0      | ProjectE-1.12-PE1.2.0.jar                     | None                                     |
	| UE    | projectred-core           | 1.0               | ProjectRed-1.12.2-4.8.6.55-deobf.jar          | None                                     |
	| UE    | projectred-transportation | 1.0               | ProjectRed-1.12.2-4.8.6.55-deobf.jar          | None                                     |
	| UE    | projectred-exploration    | 1.0               | ProjectRed-1.12.2-4.8.6.55-deobf.jar          | None                                     |
	| UE    | projectred-transmission   | 1.0               | ProjectRed-1.12.2-4.8.6.55-deobf.jar          | None                                     |
	| UE    | projectred-expansion      | 1.0               | ProjectRed-1.12.2-4.8.6.55-deobf.jar          | None                                     |
	| UE    | projectred-illumination   | 1.0               | ProjectRed-1.12.2-4.8.6.55-deobf.jar          | None                                     |
	| UE    | projectred-fabrication    | 1.0               | ProjectRed-1.12.2-4.8.6.55-deobf.jar          | None                                     |
	| UE    | projectred-integration    | 1.0               | ProjectRed-1.12.2-4.8.6.55-deobf.jar          | None                                     |
	| UC    | reborncore                | 3.6.11.220        | RebornCore-1.12.2-3.6.11.220-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UC    | reforged                  | 0.7.5             | Reforged-0.7.5-1.12+.jar                      | None                                     |
	| UC    | stevescarts               | 2.4.18.92         | StevesCarts-1.12.2-2.4.18.92.jar              | None                                     |
	| UC    | wificharge                | 1.3.0             | WirelessCharger-1.3.0.jar                     | None                                     |
	| UC    | wrcbe                     | 2.3.0             | WR-CBE-1.12.2-2.3.0.27-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | xaerominimap              | 1.14.8            | Xaeros_Minimap_1.14.8_Forge_1.12.jar          | None                                     |
| UC    | ocsensors                 | 1.0.4             | ocsensors-1.0.4-b23.jar                       | None                                     |

	Loaded coremods (and transformers): 
SoundFixPatchingLoader (AmbientSounds_v2.2.3_mc1.12.2.jar)
  com.creativemd.ambientsounds.soundfix.SoundFixTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4642' Renderer: 'Intel(R) HD Graphics 4400'

**Comment by Dushess** [comment]
Mod is not ready, please wait.

**Comment by covers1624** [comment]
I will be closing and locking further UN released 1.12 issues. Please stop using it. Btw the actual issue here, you don't have tjcore.
