### ISSUE TITLE
Crash in Relocation

### ISSUE THREAD

**Issue by VladoCC** [MrTJP/ProjectRed#1341]
`java.lang.NullPointerException: Batching chunks
	at mrtjp.projectred.relocation.MovementManager$.getWorldStructs(movement.scala:38)
	at mrtjp.projectred.relocation.MovementManager$.isMoving(movement.scala:54)
	at mrtjp.projectred.relocation.MovingBlockRenderDispatcher.func_175018_a(renders.scala:266)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745) `

Steps to reproduce:
1. Log out from the server
2. Wait
3. You crashed
Maybe it is problem with lags. My CPU were fully filled out.

**Comment by covers1624** [comment]
This was fixed ages ago, update before posting issues.

**Comment by CreeperFace00** [comment]
Having the same crash on the most recent update.  It also may have something to do with players being disconnected upon joining my server.

**Comment by CreeperFace00** [comment]
I am on the latest version (4.9.1.92) It was the first thing I did when I noticed the problem

**Comment by ignat980** [comment]
I'm getting the same issue https://pastebin.com/NWDGE1PB
