### ISSUE TITLE
Crashing when connecting and disconecting from server (4.9.1.92)

### ISSUE THREAD

**Issue by CreeperFace00** [MrTJP/ProjectRed#1358]
I am running the **latest** version of ProjectRed core and its dependents (4.9.1.92)

The problem is fairly simple, occasionally when connecting and disconnecting from my server the game crashes, it shows this stack trace:

`Description: Batching chunks 
java.lang.NullPointerException: Batching chunks
	at mrtjp.projectred.relocation.MovementManager$.getWorldStructs(movement.scala:38)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:345)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:325)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147546_a(TileEntityRendererDispatcher.java:92)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147547_b(TileEntityRendererDispatcher.java:107)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:260)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)`

[Here is the full crash report](https://gist.github.com/CreeperFace00/33a1ba47baec4e85b59a2a72562528f5)

The same issue was posted here: #1341 but again, this crash happens on the latest version of the mod

**Comment by MrTJP** [comment]
This has been fixed in dev. Wait for next release.
