### ISSUE TITLE
Crashes in Relocation not fixed.

### ISSUE THREAD

**Issue by VladoCC** [MrTJP/ProjectRed#1361]
`java.lang.NullPointerException: Batching chunks
	at mrtjp.projectred.relocation.MovementManager$.getWorldStructs(movement.scala:38)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:345)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:325)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147546_a(TileEntityRendererDispatcher.java:92)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147547_b(TileEntityRendererDispatcher.java:107)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:261)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)
`

And this is the last version of your mod.

You can say that it was fixed as much times as you want, but it is not fixed and you already goten messages about this problem,but ignored it.

See #1341

**Comment by MrTJP** [comment]
Post a valid crash log. Until then, it’s fixed.

**Comment by VladoCC** [comment]
What do you mean? This is valid crash log.

**Comment by MrTJP** [comment]
No that’s a few lines from the crash log.

**Comment by VladoCC** [comment]
Say it again! Say that you fixed it!

https://pastebin.com/5sPqj1vL

I gave you stacktrace of your crash already, but you didn't want to believe people. Better think that you are geneouse and you don't make mistakes, but this isn't truth.
You just lazy guy, which didn't want to check twice.

**Comment by covers1624** [comment]
It is fixed in dev and a release is pending.

**Comment by MrTJP** [comment]
A stack trace is not the same as a crash log. This is the first valid crash log you or anyone else has posted about this issue. I advise that you watch the way you speak here before you are blocked. You are not entitled to anything.
