### ISSUE TITLE
World breaking Crash if putting ProjectRed Lamps into an Thut's elevator i.e. as top or bottom

### ISSUE THREAD

**Issue by Psy-Virus** [MrTJP/ProjectRed#1404]
[Related Issue: Thut's Elevators](https://github.com/Thutmose/Thut/issues/120)

#### What happens:

If you have built your elevator and want to create it with the device linker and have Lamp - blocks from ProjectRed in them, the server crashes and can't be started any more until you delete the elevator via MC-Edit or something.

I'll also open an issue on PR Repo.

#### What you expected to happen:
A perfectly fine and fluid gaming ex...perie.. Well it's Minecraft.

#### Steps to reproduce:

1. Same
2. as
3. What happens
____
Crash Report, including Mod List

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 9/20/18 7:20 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: codechicken/lib/model/bakery/ModelBakery
	at mrtjp.projectred.illumination.BlockLamp.getExtendedState(blocks.scala:75)
	at thut.api.entity.blockentity.BlockEntityUpdater.applyEntityCollision(BlockEntityUpdater.java:157)
	at thut.api.entity.blockentity.BlockEntityBase.func_70108_f(BlockEntityBase.java:153)
	at thut.api.entity.blockentity.BlockEntityBase.checkCollision(BlockEntityBase.java:199)
	at thut.api.entity.blockentity.BlockEntityBase.func_70071_h_(BlockEntityBase.java:314)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.model.bakery.ModelBakery
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@d02f8d from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 17 more
Caused by: java.lang.RuntimeException: Attempted to load class codechicken/lib/model/bakery/ModelBakery for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mrtjp.projectred.illumination.BlockLamp.getExtendedState(blocks.scala:75)
	at thut.api.entity.blockentity.BlockEntityUpdater.applyEntityCollision(BlockEntityUpdater.java:157)
	at thut.api.entity.blockentity.BlockEntityBase.func_70108_f(BlockEntityBase.java:153)
	at thut.api.entity.blockentity.BlockEntityBase.checkCollision(BlockEntityBase.java:199)
	at thut.api.entity.blockentity.BlockEntityBase.func_70071_h_(BlockEntityBase.java:314)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: thuttech:lift (thut.tech.common.entity.EntityLift)
	Entity ID: 2022
	Entity Name: Elevator
	Entity's Exact location: 258.50, 4.00, 2053.50
	Entity's Block location: World: (258,4,2053), Chunk: (at 2,0,5 in 16,128; contains blocks 256,0,2048 to 271,255,2063), Region: (0,4; contains chunks 0,128 to 31,159, blocks 0,0,2048 to 511,255,2559)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['PsyVirus'/2214, l='world', x=259.81, y=9.00, z=2053.50]]
	Chunk stats: ServerChunkCache: 817 Drop: 0
	Level seed: 4209520796579142338
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (87,73,2035), Chunk: (at 7,4,3 in 5,127; contains blocks 80,0,2032 to 95,255,2047), Region: (0,3; contains chunks 0,96 to 31,127, blocks 0,0,1536 to 511,255,2047)
	Level time: 13471423 game time, 14130359 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6353 (now: true), thunder time: 53727 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-135-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 580625768 bytes (553 MB) / 2359259136 bytes (2249 MB) up to 10468982784 bytes (9984 MB)
	JVM Flags: 8 total; -Xms512M -Xmx10G -XX:NewSize=512M -XX:MaxNewSize=1G -XX:SurvivorRatio=2 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.4.2760 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                        | Version                  | Source                                          | Signature                                |
	|:--------- |:------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                 | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                       | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.4.2760-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                     | 14.23.4.2760             | forge-1.12.2-14.23.4.2760-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | itemblacklist             | 1.4.0                    | ItemBlacklist-1.4.0.jar                         | None                                     |
	| UCHIJAAAA | antiqueatlas              | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHIJAAAA | examplemod                | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHIJAAAA | applecore                 | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                    | None                                     |
	| UCHIJAAAA | jei                       | 4.11.0.212               | jei_1.12.2-4.11.0.212.jar                       | None                                     |
	| UCHIJAAAA | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJAAAA | architecturecraft         | @VERSION@                | architecturecraft-1.12-2.68.jar                 | None                                     |
	| UCHIJAAAA | autoplant                 | 1.12-1.0.0               | autoplant-1.12-1.0.0.jar                        | None                                     |
	| UCHIJAAAA | backpack                  | 3.0.2                    | backpack-3.0.2-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | bibliocraft               | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCHIJAAAA | biomesoplenty             | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar   | None                                     |
	| UCHIJAAAA | bookshelf                 | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks             | 2.4.1.73                 | ChickenChunks-1.12.2-2.4.1.73-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chisel                    | MC1.12.2-0.2.1.34        | Chisel-MC1.12.2-0.2.1.34.jar                    | None                                     |
	| UCHIJAAAA | redstoneflux              | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore                  | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld                 | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | ic2                       | 2.8.99-ex112             | industrialcraft-2-2.8.99-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | compactsolars             | 1.12.2-5.0.17.340        | CompactSolars-1.12.2-5.0.17.340-universal.jar   | None                                     |
	| UCHIJAAAA | customspawner             | 3.11.4                   | CustomMobSpawner-3.11.4.jar                     | None                                     |
	| UCHIJAAAA | customnpcs                | 1.12                     | CustomNPCs_1.12.2(26aug18).jar                  | None                                     |
	| UCHIJAAAA | ptrmodellib               | 1.0.2                    | PTRLib-1.0.2.jar                                | None                                     |
	| UCHIJAAAA | props                     | 2.6.1                    | Decocraft-2.6.1_1.12.2.jar                      | None                                     |
	| UCHIJAAAA | mocreatures               | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar             | None                                     |
	| UCHIJAAAA | dynmap                    | 2.6-beta-1-23            | dynmap.jar                                      | None                                     |
	| UCHIJAAAA | dynmapblockscan           | 3.0-alpha-1-8            | DynmapBlockScan-3.0-alpha-1-forge-1.12.2.jar    | None                                     |
	| UCHIJAAAA | eplus                     | 5.0.164                  | EnchantingPlus-1.12.2-5.0.164.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | enderstorage              | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | farseek                   | 2.3.1                    | Farseek-1.12-2.3.1.jar                          | None                                     |
	| UCHIJAAAA | forgemultipartcbe         | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe             | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar    | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe     | 2.5.0.71                 | ForgeMultipart-1.12.2-2.5.0.71-universal.jar    | None                                     |
	| UCHIJAAAA | gardenstuff               | 1.12-2.1.1               | GardenStuff-1.12-2.1.1.jar                      | None                                     |
	| UCHIJAAAA | gravestone                | 1.0.18                   | GraveStone-1.12.2-Graves-1.0.18.jar             | None                                     |
	| UCHIJAAAA | gravestone-extended       | 1.2.6                    | GraveStone-1.12.2-Extended-1.2.6.jar            | None                                     |
	| UCHIJAAAA | ichunutil                 | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJAAAA | hats                      | 7.0.0                    | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCHIJAAAA | hatstand                  | 7.0.0                    | HatStand-1.12.2-7.0.1.jar                       | None                                     |
	| UCHIJAAAA | hopperducts               | 1.5                      | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| UCHIJAAAA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | mantle                    | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHIJAAAA | mcmultipart               | 2.5.3                    | MCMultiPart-2.5.3.jar                           | None                                     |
	| UCHIJAAAA | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar         | None                                     |
	| UCHIJAAAA | nei                       | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.238-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | harvestcraft              | 1.12.2z                  | Pam's+HarvestCraft+1.12.2z.jar                  | None                                     |
	| UCHIJAAAA | sonarcore                 | 5.0.16                   | sonarcore-1.12.2-5.0.16-16.jar                  | None                                     |
	| UCHIJAAAA | practicallogistics2       | 3.0.4                    | practicallogistics2-1.12.2-3.0.4.jar            | None                                     |
	| UCHIJAAAA | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar             | None                                     |
	| UCHIJAAAA | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar           | None                                     |
	| UCHIJAAAA | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar      | None                                     |
	| UCHIJAAAA | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar      | None                                     |
	| UCHIJAAAA | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar      | None                                     |
	| UCHIJAAAA | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar         | None                                     |
	| UCHIJAAAA | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| UCHIJAAAA | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| UCHIJAAAA | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| UCHIJAAAA | projectred-exploration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar            | None                                     |
	| UCHIJAAAA | rangedpumps               | 0.5                      | rangedpumps-0.5.jar                             | None                                     |
	| UCHIJAAAA | ruins                     | 17.1                     | Ruins-1.12.2.jar                                | None                                     |
	| UCHIJAAAA | storagedrawers            | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                 | None                                     |
	| UCHIJAAAA | storagedrawersextra       | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar             | None                                     |
	| UCHIJAAAA | tconstruct                | 1.12.2-2.10.1.84         | TConstruct-1.12.2-2.10.1.84.jar                 | None                                     |
	| UCHIJAAAA | thermalfoundation         | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion          | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics           | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thutcore                  | 5.19.8                   | thutcore-1.12.2-5.19.8.jar                      | None                                     |
	| UCHIJAAAA | thutcore_compat           | 1.0                      | thutcore-1.12.2-5.19.8.jar                      | None                                     |
	| UCHIJAAAA | thuttech                  | 6.1.5                    | thuttech-1.12.2-6.1.5.jar                       | None                                     |
	| UCHIJAAAA | worldedit                 | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |
	| UCHIJAAAA | hungeroverhaul            | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar      | None                                     |

	Loaded coremods (and transformers): 
FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  farseek.core.FarseekClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['PsyVirus'/2214, l='world', x=259.81, y=9.00, z=2053.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by MrTJP** [comment]
Happening because Block#getExtendedBlockState() is being called server-side. PR is assuming only client will be using it. @covers1624 Is getExtendedBlockState suppose to be server-side safe?

**Comment by MrTJP** [comment]
Issue is on Thut's Elevators side.
