### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by ruiluth** [MrTJP/ProjectRed#1438]
This happened when I was messing around with setting up an automatic TiC smeltery with one comparator, one timer, and a few wires. I don't know how to read this, but it looks like it has some useful information. I'm pretty sure this is the fault of PR, but if it's TiC I'll take it over there instead. 

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/13/18 8:59 AM
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
	at slimeknights.tconstruct.smeltery.tileentity.TileChannel.handleBlockUpdate(TileChannel.java:273)
	at slimeknights.tconstruct.smeltery.block.BlockChannel.func_189540_a(BlockChannel.java:105)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at mrtjp.projectred.core.PropagationRun$$anonfun$finish$2.apply(propagation.scala:137)
	at mrtjp.projectred.core.PropagationRun$$anonfun$finish$2.apply(propagation.scala:137)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:315)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:971)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:971)
	at mrtjp.projectred.core.PropagationRun.finish(propagation.scala:137)
	at mrtjp.projectred.core.PropagationRun.runLoop(propagation.scala:182)
	at mrtjp.projectred.core.PropagationRun.start(propagation.scala:151)
	at mrtjp.projectred.core.WirePropagator$.propagateTo(propagation.scala:76)
	at mrtjp.projectred.core.WirePropagator$.propagateTo(propagation.scala:82)
	at mrtjp.projectred.transmission.TWireCommons$class.onNeighborChanged(wireabstracts.scala:51)
	at mrtjp.projectred.transmission.WirePart.onNeighborChanged(wireabstracts.scala:170)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:448)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:448)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:135)
	at codechicken.multipart.TileMultipart.onNeighborBlockChange(TileMultipart.scala:448)
	at codechicken.multipart.BlockMultipart.func_189540_a(BlockMultipart.scala:223)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at mrtjp.projectred.integration.RedstoneGatePart$$anonfun$notifyExternals$1.apply$mcVI$sp(gatepartrs.scala:108)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at mrtjp.projectred.integration.RedstoneGatePart.notifyExternals(gatepartrs.scala:104)
	at mrtjp.projectred.integration.RedstoneGatePart.onOutputChange(gatepartrs.scala:82)
	at mrtjp.projectred.integration.Timer.pointerTick(gatepartseq.scala:430)
	at mrtjp.projectred.integration.TTimerGateLogic$class.onTick(gatepartseq.scala:354)
	at mrtjp.projectred.integration.Timer.onTick(gatepartseq.scala:394)
	at mrtjp.projectred.integration.Timer.onTick(gatepartseq.scala:394)
	at mrtjp.projectred.integration.GatePart.func_73660_a(gatepart.scala:130)
	at codechicken.multipart.scalatraits.TTickableTile$class.update(TTickableTile.scala:58)
	at codechicken.multipart.scalatraits.JTickableTile$class.func_73660_a(TTickableTile.scala:95)
	at TileMultipart_cmp$$2.func_73660_a(Unknown Source)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at slimeknights.tconstruct.smeltery.tileentity.TileChannel.handleBlockUpdate(TileChannel.java:273)
	at slimeknights.tconstruct.smeltery.block.BlockChannel.func_189540_a(BlockChannel.java:105)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #384 (tile.null // codechicken.multipart.BlockMultipart // forgemultipartcbe:multipart_block)
	Block: tconstruct:channel[down=false,east=none,north=none,south=none,west=none]
	Block location: World: (181,65,-1349), Chunk: (at 5,4,11 in 11,-85; contains blocks 176,0,-1360 to 191,255,-1345), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at mrtjp.projectred.core.PropagationRun$$anonfun$finish$2.apply(propagation.scala:137)
	at mrtjp.projectred.core.PropagationRun$$anonfun$finish$2.apply(propagation.scala:137)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:315)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:971)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:971)
	at mrtjp.projectred.core.PropagationRun.finish(propagation.scala:137)
	at mrtjp.projectred.core.PropagationRun.runLoop(propagation.scala:182)
	at mrtjp.projectred.core.PropagationRun.start(propagation.scala:151)
	at mrtjp.projectred.core.WirePropagator$.propagateTo(propagation.scala:76)
	at mrtjp.projectred.core.WirePropagator$.propagateTo(propagation.scala:82)
	at mrtjp.projectred.transmission.TWireCommons$class.onNeighborChanged(wireabstracts.scala:51)
	at mrtjp.projectred.transmission.WirePart.onNeighborChanged(wireabstracts.scala:170)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:448)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:448)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:135)
	at codechicken.multipart.TileMultipart.onNeighborBlockChange(TileMultipart.scala:448)
	at codechicken.multipart.BlockMultipart.func_189540_a(BlockMultipart.scala:223)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:493)

-- Block being updated --
Details:
	Source block type: ID #384 (tile.null // codechicken.multipart.BlockMultipart // forgemultipartcbe:multipart_block)
	Block: forgemultipartcbe:multipart_block
	Block location: World: (181,64,-1349), Chunk: (at 5,4,11 in 11,-85; contains blocks 176,0,-1360 to 191,255,-1345), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at mrtjp.projectred.integration.RedstoneGatePart$$anonfun$notifyExternals$1.apply$mcVI$sp(gatepartrs.scala:108)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at mrtjp.projectred.integration.RedstoneGatePart.notifyExternals(gatepartrs.scala:104)
	at mrtjp.projectred.integration.RedstoneGatePart.onOutputChange(gatepartrs.scala:82)
	at mrtjp.projectred.integration.Timer.pointerTick(gatepartseq.scala:430)
	at mrtjp.projectred.integration.TTimerGateLogic$class.onTick(gatepartseq.scala:354)
	at mrtjp.projectred.integration.Timer.onTick(gatepartseq.scala:394)
	at mrtjp.projectred.integration.Timer.onTick(gatepartseq.scala:394)
	at mrtjp.projectred.integration.GatePart.func_73660_a(gatepart.scala:130)
	at codechicken.multipart.scalatraits.TTickableTile$class.update(TTickableTile.scala:58)
	at codechicken.multipart.scalatraits.JTickableTile$class.func_73660_a(TTickableTile.scala:95)
	at TileMultipart_cmp$$2.func_73660_a(Unknown Source)

-- Block entity being ticked --
Details:
	Name: ccmp:saved_multipart // TileMultipart_cmp$$2
	Block type: ID #384 (tile.null // codechicken.multipart.BlockMultipart // forgemultipartcbe:multipart_block)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (181,64,-1348), Chunk: (at 5,4,12 in 11,-85; contains blocks 176,0,-1360 to 191,255,-1345), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Actual block type: ID #384 (tile.null // codechicken.multipart.BlockMultipart // forgemultipartcbe:multipart_block)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Creative Testing
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 3046043727704567732
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock,59*minecraft:stone,3*minecraft:dirt,minecraft:grass;1;biome_1
	Level spawn location: World: (216,4,-1192), Chunk: (at 8,0,8 in 13,-75; contains blocks 208,0,-1200 to 223,255,-1185), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 43128 game time, 100764 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 29805 (now: false), thunder time: 67200 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.19.0-32-generic
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1257164768 bytes (1198 MB) / 3125235712 bytes (2980 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 5 total; -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2775 Optifine OptiFine_1.12.2_HD_U_E2 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                        | Version                 | Source                                                       | Signature                                |
	|:--------- |:------------------------- |:----------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft                 | 1.12.2                  | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | mcp                       | 9.42                    | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | FML                       | 8.0.99.99               | forge-1.12.2-14.23.5.2775.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                     | 14.23.5.2775            | forge-1.12.2-14.23.5.2775.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | hardlib                   | 7                       | 1.12.1-HardLib-v7.jar                                        | None                                     |
	| UCHIJAAAA | expindustry               | 7.0.0a                  | 1.12.1-ExpandedIndustry-7.0.0a.jar                           | None                                     |
	| UCHIJAAAA | harderfarming             | 7.0.0a                  | 1.12.1-Harderfarming-7.0.0a.jar                              | None                                     |
	| UCHIJAAAA | customoregen              | 1.12                    | CustomOreGen-1.12-1.8.1.jar                                  | None                                     |
	| UCHIJAAAA | oreflowers                | 7.0.0a                  | 1.12.1-OreFlowers-7.0.0a.jar                                 | None                                     |
	| UCHIJAAAA | harderores                | 7.0.0a                  | 1.12.1-HarderOres-7.0.0a.jar                                 | None                                     |
	| UCHIJAAAA | additionalstructures      | 1.6.0                   | Additional+Structures+1.12.2+by+XxRexRaptorxX++(v.1.6.0).jar | None                                     |
	| UCHIJAAAA | antiqueatlas              | 4.4.9                   | antiqueatlas-1.12.2-4.4.9.jar                                | None                                     |
	| UCHIJAAAA | antiqueatlasoverlay       | 1.2                     | antiqueatlas-1.12.2-4.4.9.jar                                | None                                     |
	| UCHIJAAAA | examplemod                | 1.0                     | antiqueatlas-1.12.2-4.4.9.jar                                | None                                     |
	| UCHIJAAAA | applecore                 | 3.1.4                   | AppleCore-mc1.12.2-3.1.4.jar                                 | None                                     |
	| UCHIJAAAA | charset                   | 0.5.5.6                 | Charset-Lib-0.5.5.6.jar                                      | None                                     |
	| UCHIJAAAA | jei                       | 4.13.1.222              | jei_1.12.2-4.13.1.222.jar                                    | None                                     |
	| UCHIJAAAA | appleskin                 | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                                   | None                                     |
	| UCHIJAAAA | backpack                  | 3.0.2                   | backpack-3.0.2-1.12.2.jar                                    | None                                     |
	| UCHIJAAAA | betterslabsmod            | 0.0.7                   | Better+Slabs+Mod+[0.0.7].jar                                 | None                                     |
	| UCHIJAAAA | forgelin                  | 1.8.2                   | Forgelin-1.8.2.jar                                           | None                                     |
	| UCHIJAAAA | betterfoliage             | 2.2.0                   | BetterFoliage-MC1.12-2.2.0.jar                               | None                                     |
	| UCHIJAAAA | bibliocraft               | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar                            | None                                     |
	| UCHIJAAAA | biomesoplenty             | 7.0.1.2419              | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar                | None                                     |
	| UCHIJAAAA | blockcraftery             | 1.12.2-1.1.0            | blockcraftery-1.12.2-1.1.0.jar                               | None                                     |
	| UCHIJAAAA | bookshelf                 | 2.3.568                 | Bookshelf-1.12.2-2.3.568.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | buildcraftlib             | 7.99.19                 | buildcraft-7.99.19.jar                                       | None                                     |
	| UCHIJAAAA | buildcraftcore            | 7.99.19                 | buildcraft-7.99.19.jar                                       | None                                     |
	| UCHIJAAAA | buildcraftbuilders        | 7.99.19                 | buildcraft-7.99.19.jar                                       | None                                     |
	| UCHIJAAAA | buildcraftenergy          | 7.99.19                 | buildcraft-7.99.19.jar                                       | None                                     |
	| UCHIJAAAA | buildcraftfactory         | 7.99.19                 | buildcraft-7.99.19.jar                                       | None                                     |
	| UCHIJAAAA | buildcraftrobotics        | 7.99.19                 | buildcraft-7.99.19.jar                                       | None                                     |
	| UCHIJAAAA | buildcrafttransport       | 7.99.19                 | buildcraft-7.99.19.jar                                       | None                                     |
	| UCHIJAAAA | buildcraftsilicon         | 7.99.19                 | buildcraft-7.99.19.jar                                       | None                                     |
	| UCHIJAAAA | catwalks                  | 1.12.2-4.0.42           | catwalks-1.12.2-4.0.42.jar                                   | None                                     |
	| UCHIJAAAA | codechickenlib            | 3.2.2.353               | CodeChickenLib-1.12.2-3.2.2.353-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks             | 2.4.1.73                | ChickenChunks-1.12.2-2.4.1.73-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | craftablesaddles          | 1.3                     | Craftable+Saddles[1.12]-1.3.jar                              | None                                     |
	| UCHIJAAAA | disenchanter              | 1.6                     | disenchanter-[1.12]1.6.jar                                   | None                                     |
	| UCHIJAAAA | eplus                     | 5.0.174                 | EnchantingPlus-1.12.2-5.0.174.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | enderstorage              | 2.4.5.135               | EnderStorage-1.12.2-2.4.5.135-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | fastbench                 | 1.6.0                   | FastWorkbench-1.12.2-1.6.0.jar                               | None                                     |
	| UCHIJAAAA | forgemultipartcbe         | 2.6.0.79                | ForgeMultipart-1.12.2-2.6.0.79-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe             | 2.6.0.79                | ForgeMultipart-1.12.2-2.6.0.79-universal.jar                 | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe     | 2.6.0.79                | ForgeMultipart-1.12.2-2.6.0.79-universal.jar                 | None                                     |
	| UCHIJAAAA | geographicraft            | 0.8.7                   | GeographiCraft-1.12-0.8.9b.jar                               | None                                     |
	| UCHIJAAAA | gottschcore               | 1.5.1                   | GottschCore-mc1.12.2-f14.23.5.2768-v1.5.1.jar                | None                                     |
	| UCHIJAAAA | ic2                       | 2.8.103-ex112           | industrialcraft-2-2.8.103-ex112.jar                          | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | mantle                    | 1.12-1.3.3.39           | Mantle-1.12-1.3.3.39.jar                                     | None                                     |
	| UCHIJAAAA | moarboats                 | 1.2.1                   | moarboats-1.12.2-1.2.1.jar                                   | None                                     |
	| UCHIJAAAA | mrtjpcore                 | 2.1.3.35                | MrTJPCore-1.12.2-2.1.3.35-universal.jar                      | None                                     |
	| UCHIJAAAA | nocaves                   | 1.2                     | nocaves-1.2.jar                                              | None                                     |
	| UCHIJAAAA | nei                       | 2.4.2                   | NotEnoughItems-1.12.2-2.4.2.240-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | harvestcraft              | 1.12.2z                 | Pam's+HarvestCraft+1.12.2za.jar                              | None                                     |
	| UCHIJAAAA | projectred-core           | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-Base.jar                          | None                                     |
	| UCHIJAAAA | projectred-compat         | 1.0                     | ProjectRed-1.12.2-4.9.1.92-compat.jar                        | None                                     |
	| UCHIJAAAA | projectred-integration    | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-integration.jar                   | None                                     |
	| UCHIJAAAA | projectred-transmission   | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-integration.jar                   | None                                     |
	| UCHIJAAAA | projectred-fabrication    | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-fabrication.jar                   | None                                     |
	| UCHIJAAAA | projectred-illumination   | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-lighting.jar                      | None                                     |
	| UCHIJAAAA | projectred-expansion      | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                    | None                                     |
	| UCHIJAAAA | projectred-relocation     | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                    | None                                     |
	| UCHIJAAAA | projectred-transportation | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                    | None                                     |
	| UCHIJAAAA | projectred-exploration    | 4.9.1.92                | ProjectRed-1.12.2-4.9.1.92-world.jar                         | None                                     |
	| UCHIJAAAA | roguelike                 | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar                           | None                                     |
	| UCHIJAAAA | spiceoflife               | 1.3.12                  | SpiceOfLife-mc1.12-1.3.12.jar                                | None                                     |
	| UCHIJAAAA | subterranaenwaters        | 1.12.2-1.5.6            | subh2o-1.12.2-1.5.6.jar                                      | None                                     |
	| UCHIJAAAA | twilightforest            | 3.8.689                 | twilightforest-1.12.2-3.8.689-universal.jar                  | None                                     |
	| UCHIJAAAA | tconstruct                | 1.12.2-2.11.0.106       | TConstruct-1.12.2-2.11.0.106.jar                             | None                                     |
	| UCHIJAAAA | bspkrscore                | at_0.9                  | Treecapitator-1.12-at_0.9a.jar                               | None                                     |
	| UCHIJAAAA | treecapitator             | at_0.9                  | Treecapitator-1.12-at_0.9a.jar                               | None                                     |
	| UCHIJAAAA | waystones                 | 4.0.62                  | Waystones_1.12.2-4.0.62.jar                                  | None                                     |
	| UCHIJAAAA | llibrary                  | 1.7.15                  | llibrary-1.7.15-1.12.2.jar                                   | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | hungeroverhaul            | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar                   | None                                     |
	| UCHIJAAAA | mysticallib               | 1.12.2-1.0.0            | mysticallib-1.12.2-1.0.0.jar                                 | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 352.63
	OpenGlRenderer: GeForce GTX 860M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by MrTJP** [comment]
Very little chance this is a PR bug. NPE in one of Tinker's Construct methods when the only thing being passed in is a non-null BlockPos. Will close since Tinker's source has probably changed since then so the crashlog is useless.
