### ISSUE TITLE
Crash with CC-Tweaked mod

### ISSUE THREAD

**Issue by minz1** [MrTJP/ProjectRed#1444]
Time: 1/10/19 2:34 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: mrtjp.projectred.api.ITransmissionAPI.getBundledInput(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)[B
	at mrtjp.projectred.compatibility.computercraft.CCPRBundledRedstoneProvider$.getBundledRedstoneOutput(PluginComputerCraft.scala:45)
	at dan200.computercraft.ComputerCraft.getBundledRedstoneOutput(ComputerCraft.java:799)
	at dan200.computercraft.shared.util.RedstoneUtil.getBundledRedstoneOutput(RedstoneUtil.java:25)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateSideInput(TileComputerBase.java:330)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:352)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:485)
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.writeDescription(TileComputerBase.java:532)
	at dan200.computercraft.shared.common.TileGeneric.func_189518_D_(TileGeneric.java:189)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:182)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

Crash occurs when right clicking on a Computer block from CC-Tweaked.

**Comment by minz1** [comment]
Actually, I believe the issue lies with Optifine. Sorry!
