### ISSUE TITLE
World Crashed & won't reload

### ISSUE THREAD

**Issue by jordan8396** [MrTJP/ProjectRed#1656]
**Describe the bug**
My World was working fine, then I discovered ProjectRed was finally on 1.15.2 So installed it. All was working fine for a good few hours, then the next time I open the map it immediately crashes... Apologies as this may not entirely be a project red issue, however, it is peculiar that it has only just happened after installing the mod.
I'd even appreciate it if someone could work out what the crash report is saying to find the cause (if it is not PR doing it 🙏)

**To Reproduce**
Possibly not even reproducible? 

**Expected behavior**
My world to load.

**Crash Log**

The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: null
Exit Code: -1
[crash log pastebin](https://pastebin.com/CctPNxcq)

**Versions**
* Dependancies:
CodeChickenLib-1.15.2-3.3.6.424
CBMultipart-1.15.2-3.0.0.106
Scorge-3.1.2
* ProjectRed:
ProjectRed-1.15.2-4.10.0-beta-27-core
ProjectRed-1.15.2-4.10.0-beta-27-illumination
ProjectRed-1.15.2-4.10.0-beta-27-integration
ProjectRed-1.15.2-4.10.0-beta-27-transmission
* Full list of other mods installed
[on pastebin](https://pastebin.com/jhqu9FRh)

**Screenshots/Videos**
https://user-images.githubusercontent.com/70548908/125689688-6d91e9c1-df44-4c2d-8614-35f94385f392.mp4

**Comment by MrTJP** [comment]
Don't really see a mention of Project Red in that crash log. The crash is coming from Immersive Engineering:
```
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-21.0.jar:?] {}
	at blusunrize.immersiveengineering.api.wires.utils.WireUtils.getVecForIICAt(WireUtils.java:210) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.ApiUtils.getVecForIICAt(ApiUtils.java:299) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.Connection.generateCatenaryData(Connection.java:121) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.genConnBlockstate(ImmersiveConnectableTileEntity.java:140) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.api.wires.ImmersiveConnectableTileEntity.getModelData(ImmersiveConnectableTileEntity.java:153) ~[?:?] {re:classloading}
```

I would show this to one of their devs, maybe they know what's going on.

**Comment by jordan8396** [comment]
Okay, Thank you for having a look (I have no idea what anything in crash reports actually means!). Ill contact the Immersive Enguineering devs in that case :)
