### ISSUE TITLE
4.3.7.32 crash while breaking pipes

### ISSUE THREAD

**Issue by braddr** [MrTJP/ProjectRed#413]
I've repeatedly crashed today while breaking pipes.  It's not every time, maybe 1 in 3 or 1 in 4.  Each time it's just after the break animation finishes where the parts start to fall.  In most of the cases, I've been breaking interface pipes with 2 chips in them (broadcast and responder).

From ForgeModLoader-client-0.log:

```
2014-04-19 17:26:20 [INFO] [STDERR] net.minecraft.util.ReportedException: Ticking tile entity
2014-04-19 17:26:20 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:674)
2014-04-19 17:26:20 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-04-19 17:26:20 [INFO] [STDERR]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
2014-04-19 17:26:20 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-04-19 17:26:20 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-04-19 17:26:20 [INFO] [STDERR] Caused by: mrtjp.projectred.core.utils.LabelThrowable
2014-04-19 17:26:20 [SEVERE] [Minecraft-Server] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Ticking tile entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:674)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: mrtjp.projectred.core.utils.LabelThrowable
```

From the referenced crash report:

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/19/14 5:26 PM
Description: Ticking tile entity

mrtjp.projectred.core.utils.LabelThrowable


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Tile entity being ticked --
Details:
    Name: savedMultipart // TileMultipart_cmp$$21
    Block type: ID #1281 (tile.ccmultipart // codechicken.multipart.BlockMultipart)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-959,60,-572), Chunk: (at 1,3,4 in -60,-36; contains blocks -960,0,-576 to -945,255,-561), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
    Actual block type: ID #1281 (tile.ccmultipart // codechicken.multipart.BlockMultipart)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2214)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)


Using the most recent testing release of attack of the b team:
Details:
    Minecraft Version: 1.6.4
    Operating System: Mac OS X (x86_64) version 10.9.2
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 194617800 bytes (185 MB) / 822607872 bytes (784 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 2 total; -Xmx3072m -XX:MaxPermSize=256m

    CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.0.0.250} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.3.7.32} [ProjectRed] (ProjectRedBase-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{4.3.7.32} [ProjectRed-Exploration] (ProjectRedWorld-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.3.7.32} [ProjectRed-Transmission] (ProjectRedIntegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{4.3.7.32} [ProjectRed-Transportation] (ProjectRedMechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Compatibility{4.3.7.32} [ProjectRed-Compatibility] (ProjectRedCompat-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.3.7.32} [ProjectRed-Integration] (ProjectRedIntegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{4.3.7.32} [ProjectRed-Illumination] (ProjectRedLighting-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{4.3.7.32} [ProjectRed-Expansion] (ProjectRedMechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
```

**Comment by AngryCarrot789** [comment]
this happened to me once, i was breaking routed interface pipes (with an item responder chip inside), other pipes broke fine but then 1 random pipe, as soon as i broke it the server crashed.
game version is 1.6.4.
i haven't seen the code behind the pipes but i assume the crash is something to do with the multipart tiles, maybe when it's revaluating the 'parts'. i also thought it might be because the pipes were in different chunks, but mine were in the same chunk so thats not the issue.
