### ISSUE TITLE
Black Lamps crash world with ColoredLights

### ISSUE THREAD

**Issue by TriforceOfKirby** [MrTJP/ProjectRed#687]
When placing black lamps in the world with ColoredLights compatibility enabled it crashes the world.
Crash Report:
java.lang.IndexOutOfBoundsException: 15
	at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:132)
	at scala.collection.immutable.Vector.apply(Vector.scala:122)
	at mrtjp.projectred.illumination.IlluminationProxy_client.makeRGBLightValue(proxies.scala:121)
	at mrtjp.projectred.illumination.TileLamp.getLightValue(blocks.scala:100)
	at mrtjp.core.block.InstancedBlock.getLightValue(tileblock.scala:292)
	at net.minecraft.block.Block.func_149677_c(Block.java:528)
	at coloredlightscore.src.helper.CLRenderBlocksHelper.renderStandardBlockWithAmbientOcclusion(CLRenderBlocksHelper.java:372)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at fastcraft.m.a(Unknown Source)
	at fastcraft.Hooks.t(Unknown Source)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MrTJP** [comment]
Fixed via 9c5f5e948d99c39347177c7df9e8a160c76e11d2
