### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by VitorH** [MrTJP/ProjectRed#716]
I reiceved this error when after install ProjectRED (I installed MrTJP before P:RED. I installed it, opened game, installed other mods, opened game again, and installed Project:RED before.)

---- Minecraft Crash Report ----
// Sorry :(

Time: 12/02/15 17:42
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderBlocks
	at net.minecraft.client.renderer.entity.Render.<init>(SourceFile:26)
	at net.minecraft.client.renderer.entity.RenderItem.<init>(RenderItem.java:46)
	at net.minecraft.client.gui.achievement.GuiAchievement.<init>(SourceFile:29)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:469)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.RenderBlocks
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: mrtjp/relocation/BlockMotor
	at mrtjp.relocation.RelocationMod$.<init>(mod.scala:25)
	at mrtjp.relocation.RelocationMod$.<clinit>(mod.scala)
	at mrtjp.relocation.asm.Transformer.transform(transformer.scala:85)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 14 more
Caused by: java.lang.ClassNotFoundException: mrtjp.relocation.BlockMotor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: mrtjp/core/block/InstancedBlock
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more
Caused by: java.lang.ClassNotFoundException: mrtjp.core.block.InstancedBlock
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.Render.<init>(SourceFile:26)
	at net.minecraft.client.renderer.entity.RenderItem.<init>(RenderItem.java:46)
	at net.minecraft.client.gui.achievement.GuiAchievement.<init>(SourceFile:29)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:469)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40-ea, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 80736800 bytes (76 MB) / 206712832 bytes (197 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7700 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

------------------------------------------------------------------------------------------------

I think i is an error in Block Instance or/and BlockMotor.

**Comment by simon816** [comment]
You've installed the dev version in a obfuscated environment. Please use the standard downloads.
The dev version is only for people who wish to develop mods with PR.

**Comment by VitorH** [comment]
Oh, you're talking about the red options? Sorry, for that... I downloaded them exactly because of the changes: **- FIX: Crash on world generation**. :P

Thanks :)

**Comment by VitorH** [comment]
Oops. I changed MrTJP to version 1.0.3.5 and ProjectRED to 4.5.8.59 and the error continues.

Crash report:

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 12/02/15 18:08
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderBlocks
	at net.minecraft.client.renderer.entity.Render.<init>(SourceFile:26)
	at net.minecraft.client.renderer.entity.RenderItem.<init>(RenderItem.java:46)
	at net.minecraft.client.gui.achievement.GuiAchievement.<init>(SourceFile:29)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:469)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.RenderBlocks
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: mrtjp/relocation/BlockMotor
	at mrtjp.relocation.RelocationMod$.<init>(mod.scala:25)
	at mrtjp.relocation.RelocationMod$.<clinit>(mod.scala)
	at mrtjp.relocation.asm.Transformer.transform(transformer.scala:85)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 14 more
Caused by: java.lang.ClassNotFoundException: mrtjp.relocation.BlockMotor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: mrtjp/core/block/InstancedBlock
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more
Caused by: java.lang.ClassNotFoundException: mrtjp.core.block.InstancedBlock
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.Render.<init>(SourceFile:26)
	at net.minecraft.client.renderer.entity.RenderItem.<init>(RenderItem.java:46)
	at net.minecraft.client.gui.achievement.GuiAchievement.<init>(SourceFile:29)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:469)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40-ea, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 74868424 bytes (71 MB) / 191971328 bytes (183 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7700 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by simon816** [comment]
I did not mean the red builds, I meant the jar file you downloaded was the developer version, not the player version.
On the download page, there is
* Normal downloads
* Dev download
* Sources download

I think you have the dev version of MrTJPCore, replace it with the normal download.
If that doesn't work, post your fml client log (pastebin) so I can see more information about your set-up.

**Comment by VitorH** [comment]
Well, I download with this link:
![screenshot_15](https://cloud.githubusercontent.com/assets/2721565/6176482/6ef4921c-b2e6-11e4-9778-6d60c307cc67.png)

and i tried to send my fml log, but "Pastebin.com is under heavy load right now", so it is here: http://chopapp.com/#foupt8lt

**Comment by simon816** [comment]
Ahh OK, my mistake.
Your MrTJPCore jar is corrupt, delete it and let it auto-download. If it can't auto-download then download from the website manually.
```
[18:40:13] [main/DEBUG] [FML/]: Examining for coremod candidacy MrTJPCore-1.7.10-1.0.5.11-universal.jar
[18:40:13] [main/ERROR] [FML/]: Unable to read the jar file MrTJPCore-1.7.10-1.0.5.11-universal.jar - ignoring
java.io.FileNotFoundException: C:\Users\Vitor Mattos\AppData\Roaming\.minecraft\mods\MrTJPCore-1.7.10-1.0.5.11-universal.jar (O sistema não pode encontrar o arquivo especificado)
```

**Comment by VitorH** [comment]
Hm, okey. I thought it was not possible to read this file because it was automatically moved to *.minecraft/mods/1.7.10*

Thank you again

**Comment by VitorH** [comment]
OMG, I give up. I deleted MrTJP, and he was automatically downloaded, but my Minecraft crashed again. I'll try the fresh install.

**Comment by VitorH** [comment]
Hm, I think it is not a ProjectRed error. I'm getting other error in my new install. My game is running with 1fps, but when a open menu (hitting ESC), fps go to 60/70. Apologize for the inconvenience.

**Comment by Mach12** [comment]
I'm sorry but I'll have to insist for this ticket to be reopened.

Crash obtained with:
Project Red 4.6.2.82
Forge Multipart 1.2.0.344 (tried both manual and automatic download)
MrTJPCore 1.0.8.16 (same as above)

I only used recommended (green) builds and those marked "universal" for manual downloads.
All these versions of the mods were marked as the latest stable builds on Friday, May the 29th.

Pastebin to the crash report:
http://pastebin.com/bSWBigGb

According to the stacktrace, this is a Relocation error, not a MrTJPCore error (unless Relocation methods and classes are to be found in MrTJPCore).

**Comment by kenzierocks** [comment]
You need .334 still I believe, not .344 of FMP.

-- 
~Kenzie Togami

**Comment by Mach12** [comment]
I don't understand. What version of what do I need?

**Comment by kenzierocks** [comment]
Forge Multipart ending in .334. What it was before 4dd72735067e7c63d68f94db3a383e5fabdcd758.

**Comment by MrTJP** [comment]
Latest version of PR should work find with FMP 344.
@Mach12 You have all of the proper versions required. This crash can be happening for one of the following reasons:
1) You have the dev version of one of the jar files. These versions are not for you. Simply delete it and download the right version.
2) You have another mod installed thats messing you up. Try it with JUST PR and see if it works.

**Comment by Mach12** [comment]
The versions I'm afraid to tell you that the error comes from a lack of accuracy in your solutions.

Both my version (the one automatically downloaded) of FMP and the one imported before this commit:
https://github.com/MrTJP/ProjectRed/commit/4dd72735067e7c63d68f94db3a383e5fabdcd758
Have a number ending in .334 .

After checking my theory, I can confirm that the version of FMP that is both "recommended" and automatically downloaded is __1.2.0__.334 , whereas the latest PR is very likely build against FMP __1.1.2__.334 .

I think I can assert that the fact that PR downloads the wrong FMP automatically is misbehaving automation.

In the future, I'd advise you to give full version number if both end with the same digits.

**Comment by MrTJP** [comment]
They don't end in the same number. One is 1.2.0.344 and the other is 1.1.2.334. The latest version of PR works with the latest version of FMP.

And again, try to remove Relocation.

**Comment by Mach12** [comment]
Oh my bad for the number. It's late here and I'm tired, must have misread.

Though I still mean the rest. PR *did* download the wrong version. It needed 334 and took 344 if let downlading automatically.
