### ISSUE TITLE
Problem between ProjectRed and Forge Microblocks

### ISSUE THREAD

**Issue by NitroxydeX** [MrTJP/ProjectRed#795]
A user getting this error when he tries to join the server.

```
java.lang.AbstractMethodError: mrtjp.projectred.transmission.JacketedHighlightRenderer$.renderHighlight(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/MovingObjectPosition;Lcodechicken/microblock/CommonMicroClass;II)Z
	at codechicken.microblock.MicroMaterialRegistry$$anonfun$2.apply(MicroMaterialRegistry.scala:233)
	at codechicken.microblock.MicroMaterialRegistry$$anonfun$2.apply(MicroMaterialRegistry.scala:233)
	at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:99)
	at scala.collection.immutable.List.find(List.scala:83)
	at scala.collection.generic.TraversableForwarder$class.find(TraversableForwarder.scala:43)
	at scala.collection.mutable.ListBuffer.find(ListBuffer.scala:45)
	at codechicken.microblock.MicroMaterialRegistry$.renderHighlight(MicroMaterialRegistry.scala:233)
	at codechicken.microblock.ItemMicroPartRenderer$.renderHighlight(ItemMicroPart.scala:168)
	at codechicken.microblock.handler.MicroblockEventHandler$.drawBlockHighlight(MicroblockEventHandler.scala:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_556_MicroblockEventHandler$_drawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Looked in his player dat. He had a torch in his hand. This crashed the game?

**Comment by MrTJP** [comment]
Downgrade FMP a or wait for a PR update.
