### ISSUE TITLE
Cant remove Saws from Prject red with Minetweaker

### ISSUE THREAD

**Issue by Dream-Master** [MrTJP/ProjectRed#811]
I try to remove the Saws because i want to change the Recipes and get the following Error.
Why it have a Space between the Double Point ?

The Same with Inguana Tinkers Saws

````````````````````````````````````````````````````````````````````````````````
ERROR: Error executing Project_Red.zs: null
java.lang.NullPointerException
	at minetweaker.mc1710.recipes.MCRecipeManager.remove(MCRecipeManager.java:94)
	at Project_Red.__script__(Project_Red.zs:128)
	at __ZenMain__.run(Project_Red.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

``````````````````````````````````````````````

https://github.com/SlimeKnights/IguanaTweaksTConstruct/issues/149

https://github.com/stanhebben/MineTweaker3/issues/194

**Comment by MrTJP** [comment]
Report it to MineTweaker, I guess. Not my problem.

**Comment by Dream-Master** [comment]
I did the link below show it.

**Comment by Dream-Master** [comment]
@MrTJP 
Iguana Tweaks saws working now with Minetweaker 3.0.10 but not yours.
When you saws got to be rgistered that i can ask at minetweaker side or what you do different then iguana tweaks?

**Comment by Dream-Master** [comment]
Ok problem is solved
