### ISSUE TITLE
ConcurrentModificationException with new PR version

### ISSUE THREAD

**Issue by SanAndreasP** [MrTJP/ProjectRed#815]
Minecraft: 1.7.10
Forge: 10.13.4.1451

I recently updated ProjectRed to 4.7.0pre2.87 and upon loading my world, I crash with this stack trace:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:46)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1205_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.c.p.a(F:19)
	at fastcraft.Hooks.aq(F:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

I don't have this crash on an earlier version (4.7.0pre1.84).

Here's the complete log:
https://gist.githubusercontent.com/SanAndreasP/0005cc26b27246e5d1bb/raw/gistfile1.txt

Hope you can fix it :)

**Comment by MrTJP** [comment]
Again, update MrTJPCore.

**Comment by SanAndreasP** [comment]
geez... I thought I updated it to 22, but apparently I was still on 19...
Also I should look at the closed issues first next time <.<

Sorry for wasting your time D:
