### ISSUE TITLE
Crash "Exception in server tick loop"

### ISSUE THREAD

**Issue by orangecup** [MrTJP/ProjectRed#820]
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/19/15 12:28 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:46)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_626_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 553767672 bytes (528 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1470 96 mods loaded, 96 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1470-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1470} [Minecraft Forge] (forge-1.7.10-10.13.4.1470-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-9} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAA	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-9} [Applied Energistics 2] (appliedenergistics2-rv2-stable-9.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
	UCHIJAAAA	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Botania{r1.6-192} [Botania] (Botania r1.6-192.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.11} [BuildCraft] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.11} [BC Energy] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.11} [BC Factory] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.11} [BC Robotics] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.11} [BC Silicon] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.11} [BC Transport] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.11} [BC Builders] (buildcraft-7.0.11.jar) 
	UCHIJAAAA	IC2{2.2.736-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.736-experimental.jar) 
	UCHIJAAAA	Forestry{3.5.7.16} [Forestry for Minecraft] (forestry_1.7.10-3.5.7.16.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.0.8} [BuildCraft Compat] (buildcraft-compat-7.0.8.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.6} [Extra Utilities] (extrautilities-1.2.6.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.0.9.19} [MrTJPCore] (MrTJPCore-1.7.10-1.0.9.19-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre2.87} [ProjectRed] (ProjectRed-1.7.10-4.7.0pre2.87-Base.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre2.87} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.7.0pre2.87-World.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJAAAA	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) 
	UCHIJAAAA	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) 
	UCHIJAAAA	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre2.87} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.7.0pre2.87-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre2.87} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.7.0pre2.87-Mechanical_beta.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre2.87} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.7.0pre2.87-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre2.87} [ProjectRed-Integration] (ProjectRed-1.7.10-4.7.0pre2.87-Integration.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre2.87} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.7.0pre2.87-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre2.87} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.7.0pre2.87-Mechanical_beta.jar) 
	UCHIJAAAA	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCHIJAAAA	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
	UCHIJAAAA	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) 
	UCHIJAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAA	VersionChecker{1.1.9} [Version Checker] (VersionChecker-1.1.9(1.7.10).jar) 
	UCHIJAAAA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	aobd{2.6.3} [Another One Bites The Dust] (AOBD-2.6.3.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-9 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.0.0-122
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['log_man88'/193, l='Testing LPack 1.2', x=236.50, y=66.00, z=246.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by MrTJP** [comment]
Refer to last 5 closed issues.
