### ISSUE TITLE
Crash ConcurrentModificationException

### ISSUE THREAD

**Issue by MySt1k** [MrTJP/ProjectRed#823]
http://pastebin.com/Ufa4XvK0

**Comment by richardcox13** [comment]
Can confirm. Each time shortly – no more than a few minutes – after loading up a world.

Having fixed the AbstractMethodError in mrtjp.projectred.transmission.JacketedHighlightRenderer$.renderHighlight by updating to the latest PR I get this: one bug fixed, another one appears :-(.

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:46)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_726_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Full log available on request.

**Comment by MrTJP** [comment]
Update MrTJPCore. Also, no offense intended, you should at least *glance* at the last few closed issues before reporting anything.
