### ISSUE TITLE
Server disconnect / SP crash - extractor chip - index out of boundry

### ISSUE THREAD

**Issue by Terpo** [MrTJP/ProjectRed#829]
MC: 1.7.10
Forge: 1448
Project Red: 4.6.2.82 

--------------------------------------------------------------------------

I'm getting a disconnect from our server / crash in singleplayer when trying to set / click into the itemfilter of an Item Extractor Chip.

--------------------------------------------------------------------------

SP crash: 
crash-2015-06-28_21.59.34-server.txt -> http://pastebin.com/Hf0fPpS6

MP server disconnect log (serverside)
[21:55:03] [Server thread/WARN]: Failed to handle packet for /93.218.130.54:2315
java.lang.IndexOutOfBoundsException: Index: 40, Size: 36
at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_45]
at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_45]
at net.minecraft.inventory.Container.func_75144_a(SourceFile:206) ~[zs.class:?]
at mrtjp.core.gui.WidgetContainer.func_75144_a(WidgetContainer.scala:61) ~[WidgetContainer.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883) ~[nh.class:?]
at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by MrTJP** [comment]
Update *before* reporting things.
