### ISSUE TITLE
Deviating Lily texture error

### ISSUE THREAD

**Issue by Caeldeth** [MrTJP/ProjectRed#832]
When creating a resource pack for project red, the deviating lily cannot be re-sized beyond 16x16.  Doing so results in this error:
[02:57:05] [Client thread/INFO]: Caught error stitching, removing all assigned resourcepacks
net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:91) ~[bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136) ~[bqf.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143) ~[brg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121) ~[brg.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:609) [bao.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.RuntimeException: broken aspect ratio and not an animation
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147964_a(TextureAtlasSprite.java:215) ~[bqd.class:?]
	at codechicken.lib.render.TextureSpecial.func_147964_a(TextureSpecial.java:115) ~[TextureSpecial.class:?]
	at codechicken.lib.render.TextureSpecial.addFrame(TextureSpecial.java:135) ~[TextureSpecial.class:?]
	at codechicken.lib.render.TextureSpecial.load(TextureSpecial.java:142) ~[TextureSpecial.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:117) ~[bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) ~[bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) ~[bqf.class:?]
	... 14 more

Log files: 
http://pastebin.com/Rk9U0gqy
http://pastebin.com/2Y7wk3Q3

I have a much larger mod pack I'm retexturing, and isolating this was... fun.

**Comment by MrTJP** [comment]
Oh yes.. When I first made the textures I was playing around with dynamic generation of the coloured center of the lily. Forgot to change that...

**Comment by MrTJP** [comment]
Fixed via 57cded5ca6f448727f635256e81bc20a1429b4ba
