### ISSUE TITLE
ProjectRed not working offline

### ISSUE THREAD

**Issue by MacDaddy12** [MrTJP/ProjectRed#897]
Hello, I have added ProjectRed to my mods, and ive had countless issues, well I finally fixed them all, except one major one. It crashes when I try to start a game offline. I don't have wifi at my house, and currently using a library's internet. Well with all my mods, online they work just fine. When I go offline though to check if they work, Project red is the only mods I saw that had the "E" by them meaning error. 

here is the crash report: 

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 7/29/15 7:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.net.UnknownHostException: raw.githubusercontent.com
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1103)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:987)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:985)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:984)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1429)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1428)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at mrtjp.core.data.UpdateChecker$class.downloadVersions(UpdateChecker.scala:36)
	at mrtjp.projectred.core.PRUpdateChecker.downloadVersions(PRUpdateChecker.scala:5)
	at mrtjp.core.data.UpdateChecker$class.$init$(UpdateChecker.scala:31)
	at mrtjp.projectred.core.PRUpdateChecker.<init>(PRUpdateChecker.scala:5)
	at mrtjp.projectred.core.CoreProxy_client.postinit(proxies.scala:51)
	at mrtjp.projectred.ProjectRedCore$.postInit(ProjectRedCore.scala:43)
	at mrtjp.projectred.ProjectRedCore.postInit(ProjectRedCore.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 178032256 bytes (169 MB) / 464048128 bytes (442 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_B7 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJ	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.3.74} [Not Enough Items] (Not-Enough-Items-1.7.10.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) 
	UCHIJ	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFH-Core-1.7.10.jar) 
	UCHIJ	BuildCraft|Core{7.0.17} [BuildCraft] (buildcraft-7.0.17.jar) 
	UCHIJ	BuildCraft|Factory{7.0.17} [BC Factory] (buildcraft-7.0.17.jar) 
	UCHIJ	BuildCraft|Energy{7.0.17} [BC Energy] (buildcraft-7.0.17.jar) 
	UCHIJ	BuildCraft|Silicon{7.0.17} [BC Silicon] (buildcraft-7.0.17.jar) 
	UCHIJ	BuildCraft|Builders{7.0.17} [BC Builders] (buildcraft-7.0.17.jar) 
	UCHIJ	BuildCraft|Robotics{7.0.17} [BC Robotics] (buildcraft-7.0.17.jar) 
	UCHIJ	BuildCraft|Transport{7.0.17} [BC Transport] (buildcraft-7.0.17.jar) 
	UCHIJ	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJ	fossil{1.7.10 Build 6.3b} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-6.3b.jar) 
	UCHIJ	IC2{2.2.657-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	UCHIJ	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJ	jcanimation{1.2.4} [JCAnimationAPI] (JurassiCraft-1.4.5.jar) 
	UCHIJ	llibrary{0.3.3} [LLibrary] (LLibrary-0.3.3-1.7.10.jar) 
	UCHIJ	jurassicraft{1.4.5} [JurassiCraft] (JurassiCraft-1.4.5.jar) 
	UCHIJ	malisiscore{1.7.10-0.12.5} [MalisisCore] (malisiscore-1.7.10-0.12.5.jar) 
	UCHIJ	malisisdoors{1.7.10-1.9.3} [Malisis' Doors] (malisisdoors-1.7.10-1.9.3.jar) 
	UCHIJ	examplemod{1.0} [Example Mod] (mod_XrayV2.01.jar) 
	UCHIJ	Kradxns Xray{2.0} [Xray] (mod_XrayV2.01.jar) 
	UCHIJ	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJ	ProjectE{1.7.10-PE1.7.2} [ProjectE] (ProjectE-1.7.10-PE1.7.2.jar) 
	UCHIJ	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJ	MrTJPCoreMod{1.1.0.30} [MrTJPCore] (MrTJPCore-1.1.0.30-universal.jar) 
	UCHIE	ProjRed|Core{4.7.0pre7.91} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre7.91-Base.jar) 
	UCHIE	ProjRed|Transmission{4.7.0pre7.91} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre7.91-Integration.jar) 
	UCHIE	ProjRed|Transportation{4.7.0pre7.91} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre7.91-Mechanical.jar) 
	UCHIE	ProjRed|Exploration{4.7.0pre7.91} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre7.91-World.jar) 
	UCHIE	ProjRed|Compatibility{4.7.0pre7.91} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre7.91-Compat.jar) 
	UCHIE	ProjRed|Integration{4.7.0pre7.91} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre7.91-Integration.jar) 
	UCHIE	ProjRed|Illumination{4.7.0pre7.91} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre7.91-Lighting.jar) 
	UCHIE	ProjRed|Expansion{4.7.0pre7.91} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre7.91-Mechanical.jar) 
	UCHIJ	securitycraft{v1.7.0} [SecurityCraft] (SecurityCraft-Mod-1.7.10 (1).jar) 
	UCHIJ	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJ	Treecapitator{1.7.10} [Treecapitator] (Tree-Capitator-Mod-1.7.10.jar) 
	UCHIJ	Waila{1.5.3} [Waila] (Waila-Mod-1.7.10.jar) 
	UCHIJ	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCHIJ	XaeroMinimap{1.5.3.1} [Xaero's Minimap] (xaeros_minimap_v1.5.3.1_1.7.10_Forge.jar) 
	UCHIJ	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJ	ForgeRelocation{0.0.1.3} [ForgeRelocation] (ForgeRelocation-0.0.1.3-universal.jar) 
	UCHIJ	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.3-universal.jar) 
	UCHIJ	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJ	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	CoFHCore: -[1.7.10]3.0.2-262

**Comment by MrTJP** [comment]
Fixed in MrTJPCore
