### ISSUE TITLE
NPE when placing IC gate

### ISSUE THREAD

**Issue by CarsonF** [MrTJP/ProjectRed#915]
```
java.lang.NullPointerException: Unexpected error
        at mrtjp.projectred.fabrication.TTimerGateLogic$class.getTotalTime(gatepartseq.scala:322)
        at mrtjp.projectred.fabrication.Timer.getTotalTime(gatepartseq.scala:388)
        at mrtjp.projectred.fabrication.TTimerGateLogic$class.load(gatepartseq.scala:293)
        at mrtjp.projectred.fabrication.Timer.load(gatepartseq.scala:388)
        at mrtjp.projectred.fabrication.TComplexGateICPart$class.load(gatepart.scala:275)
        at mrtjp.projectred.fabrication.SequentialGateICPart.load(gatepartseq.scala:15)
        at mrtjp.projectred.fabrication.IntegratedCircuit$$anonfun$load$2.apply$mcVI$sp(ic.scala:238)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at mrtjp.projectred.fabrication.IntegratedCircuit.load(ic.scala:233)
        at mrtjp.projectred.fabrication.ItemICBlueprint$.loadIC(items.scala:95)
        at mrtjp.projectred.fabrication.CircuitGateLogic$.constructICLogic(fmpgatepart.scala:267)
        at mrtjp.projectred.fabrication.CircuitGatePart.preparePlacement(fmpgatepart.scala:59)
        at mrtjp.projectred.integration.ItemPartGate.newPart(items.scala:41)
        at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:32)
        at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
        at mrtjp.projectred.integration.ItemPartGate.mrtjp$core$item$TItemSound$$super$onItemUse(items.scala:26)
        at mrtjp.core.item.TItemSound$class.onItemUse(coreitem.scala:32)
        at mrtjp.projectred.integration.ItemPartGate.func_77648_a(items.scala:26)
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
        at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

I can upload a screenshot of my schematic if needed

**Comment by MalkContent** [comment]
that might help

**Comment by bosto2** [comment]
Any news when this will get fixed?
