### ISSUE TITLE
Client crash when sawing inverted lamp.

### ISSUE THREAD

**Issue by adPasya** [MrTJP/ProjectRed#975]
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 12.12.15 20:49
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 16
	at net.minecraft.block.Block.getHarvestLevel(Block.java:2211)
	at codechicken.microblock.BlockMicroMaterial.getCutterStrength(BlockMicroMaterial.scala:107)
	at codechicken.microblock.MicroRecipe$.canCut(MicroRecipe.scala:152)
	at codechicken.microblock.MicroRecipe$.getThinningResult(MicroRecipe.scala:169)
	at codechicken.microblock.MicroRecipe$.func_77572_b(MicroRecipe.scala:26)
	at codechicken.microblock.MicroRecipe$.func_77569_a(MicroRecipe.scala:18)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:80)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.Block.getHarvestLevel(Block.java:2211)
	at codechicken.microblock.BlockMicroMaterial.getCutterStrength(BlockMicroMaterial.scala:107)
	at codechicken.microblock.MicroRecipe$.canCut(MicroRecipe.scala:152)
	at codechicken.microblock.MicroRecipe$.getThinningResult(MicroRecipe.scala:169)
	at codechicken.microblock.MicroRecipe$.func_77572_b(MicroRecipe.scala:26)
	at codechicken.microblock.MicroRecipe$.func_77569_a(MicroRecipe.scala:18)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:80)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Skiarand'/5238, l='MpServer', x=170,10, y=66,62, z=221,62]]
	Chunk stats: MultiplayerChunkCache: 413, 413
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (92,64,256), Chunk: (at 12,4,0 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 385306 game time, 466062 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 13 total; [EntityCaveSpider['Cave Spider'/305, l='MpServer', x=12,90, y=-22,62, z=-10,62], EntityClientPlayerMP['Skiarand'/5238, l='MpServer', x=170,10, y=66,62, z=221,62], EntityVillager['Villager'/139, l='MpServer', x=156,31, y=71,00, z=245,53], EntityVillager['Villager'/141, l='MpServer', x=174,60, y=65,00, z=236,67], EntitySkeleton['Skeleton'/3533, l='MpServer', x=191,44, y=45,00, z=214,91], EntityCreeper['Creeper'/5365, l='MpServer', x=167,50, y=30,00, z=227,50], EntityCaveSpider['Cave Spider'/596, l='MpServer', x=42,90, y=-19,62, z=-24,62], EntityCaveSpider['Cave Spider'/3966, l='MpServer', x=168,21, y=45,00, z=207,69], EntityVillager['Villager'/127, l='MpServer', x=165,50, y=68,00, z=235,88], EntityVillager['Villager'/125, l='MpServer', x=163,50, y=68,60, z=227,35], EntityCaveSpider['Cave Spider'/4548, l='MpServer', x=183,13, y=44,00, z=212,97], EntityCaveSpider['Cave Spider'/4546, l='MpServer', x=190,00, y=45,00, z=208,00], EntityCaveSpider['Cave Spider'/4547, l='MpServer', x=178,41, y=44,00, z=207,41]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.16.0-4-amd64
	Java Version: 1.7.0_91, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 284283424 bytes (271 MB) / 631922688 bytes (602 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 11 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024M -Xmn128M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:-UseGCOverheadLimit -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xms256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448.jar) 
	UCHIJA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJA	IC2{2.2.808-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.808-experimental.jar) 
	UCHIJA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 8600 GT/PCIe/SSE2 GL version 3.3.0 NVIDIA 340.96, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by adPasya** [comment]
Sorry, didn't notice this is already solved.
